run:
  tests: false
  timeout: 5m

linters-settings:
  cyclop:
    max-complexity: 12
    skip-tests: true
  funlen:
    lines: 80
  gofumpt:
    extra-rules: true

linters:
  enable-all: true
  disable:
    - tenv # deprecated
    - contextcheck
    - depguard
    - err113
    - exhaustive
    - exhaustruct
    - forcetypeassert
    - funlen
    - gochecknoglobals
    - gochecknoinits
    - inamedparam
    - ireturn
    - mnd
    - nlreturn
    - varnamelen
    - wrapcheck
    - wsl

issues:
  exclude-use-default: false