version: "2"

formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
  settings:
    gofumpt:
      extra-rules: true
    gci:
      sections:
        - standard
        - default
        - blank
        - dot
  exclusions:
    generated: lax

linters:
  default: all
  disable:
    - contextcheck
    - depguard
    - err113
    - exhaustive
    - exhaustruct
    - forcetypeassert
    - funlen
    - gochecknoglobals
    - gochecknoinits
    - inamedparam
    - ireturn
    - mnd
    - noinlineerr
    - nonamedreturns
    - nlreturn
    - paralleltest
    - testpackage
    - varnamelen
    - wrapcheck
    - wsl
    - wsl_v5
  settings:
    cyclop:
      max-complexity: 15
    funlen:
      lines: 160
  exclusions:
    generated: lax
    rules:
      - linters:
          - gosec
          - lll
        path: _test\.go
